# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
    ignore:
      - dependency-name: "typescript"
      - dependency-name: "@backstage/*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "npm"
    directory: "/packages/app"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
    ignore:
      - dependency-name: "typescript"
      - dependency-name: "@backstage/*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "npm"
    directory: "/packages/backend" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
    ignore:
      - dependency-name: "typescript"
      - dependency-name: "@backstage/*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Asia/Tokyo"
