apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: terraform-azure-sample
  title: Terraform Azure サンプルテンプレート
  description: Terraform (Azure) 構成のサンプルテンプレートです。Resource Group、Storage Account、CosmosDB を作成するTerraform構成ファイルを含むGitHubリポジトリを作成します。（Terraformデプロイは対象外です）
spec:
  owner: group:guests
  type: infrastructure

  parameters:
    - title: Terraform構成情報の入力
      required:
        - prefix
      properties:
        prefix:
          title: リソースプレフィックス
          type: string
          description: Azureリソース名に使用するプレフィックスを入力してください（英小文字・数字のみ、3〜24文字）。
          ui:autofocus: true
          pattern: '^[a-z0-9]{3,24}$'
    - title: GitHubリポジトリの設定
      required:
        - repoUrl
      properties:
        repoUrl:
          title: リポジトリの作成先
          type: string
          description: 作成先のGitHub Organization名またはユーザーアカウント名とリポジトリ名を指定してください。対象ホストは github.com のみとなります。
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          prefix: ${{ parameters.prefix }}
          name: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
          repoUrl: ${{ parameters.repoUrl }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: Terraform Azure サンプルリポジトリ
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
