auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

backend:
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

integrations:
  github:
    - host: github.com
      apps:
        - $include: ${GITHUB_CREDENTIAL_FILE}

catalog:
  # 個人アカウントにGitHubAppを作成した場合は以下の部分をコメントアウトしてください
  providers:
    githubOrg:
      id: 'github-local'
      orgs:
      - ${GITHUB_ORG}
